# Generated by Django 2.0.5 on 2019-04-19 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avgIc', models.CharField(max_length=255)),
                ('avgAbsIc', models.CharField(max_length=255)),
                ('avgPositiveIc', models.CharField(max_length=255)),
                ('positiveIcRatio', models.CharField(max_length=255)),
                ('ir', models.CharField(max_length=255)),
                ('tStatistic', models.CharField(max_length=255)),
                ('gradingRankIC', models.CharField(max_length=255)),
                ('avgTurnOverRate', models.CharField(max_length=255)),
                ('medianTurnOverRate', models.CharField(max_length=255)),
                ('excessCumReturn_benchMark', models.CharField(max_length=255)),
                ('excessCumReturn_winAndLoss', models.CharField(max_length=255)),
                ('excessAnnualReturn_benchMark', models.CharField(max_length=255)),
                ('excessAnnualReturn_winAndLoss', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Reporter'),
        ),
    ]
